### ISSUE TITLE
Image scaling to fit the width of the window doesn't work using FireFox

### ISSUE THREAD

**Issue by dc42** [Duet3D/Closed-Loop-Plugin#3] opened 2021-12-08 11:31 UTC
If I collect 10000 samples, then if using FireFox the data chart doesn't show me the whole range of the graph even with the blue dots at the extremities of the line. I have to make the window very wide to see the whole chart. This problem does not occur if I use Chrome.

**Comment by T3P3** [comment] 2021-12-08 11:36
duplicate of #2

**Closed by T3P3** 2021-12-08 11:36 UTC
